M48
; DRILL file {KiCad (6.0.1)} date Sat Jan 13 19:57:17 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-13T19:57:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X64.99Y-65.0
X64.99Y-135.0
X130.99Y-69.0
X134.99Y-135.0
T0
M30
